name: Build TC
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add SSH KEY
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Build TC
      run: bash ci.sh all
